#############################################################
## JOB DESCRIPTION                                         ##
#############################################################

# Filling UIO66-water-tip4


#############################################################
## ADJUSTABLE PARAMETERS                                   ##
#############################################################

structure          ../uio66-water-cubo.psf
coordinates        ../uio66-water-cubo_Zr-fix.pdb
#binvelocities      ../NVE/NVE-sE.vel
#bincoordinates     ../NVE/NVE-sE.coor
#firsttimestep      0 ;#activar si es una continuación de una simulacion anterior.

set temperature    305
set outputname     NVT-305K

firsttimestep      20


#############################################################
## SIMULATION PARAMETERS                                   ##
#############################################################

# Input
paraTypeCharmm	    on
parameters          ../par_file_uio66.inp 
parameters          ../par_file_water_TIP4P.inp 
temperature         $temperature
seed 1730371550
COMmotion no

# Force-Field Parameters
exclude             scaled1-4
onefourscaling      0.000001
cutoff              12.0
switching           off
switchdist          14.0
pairlistdist        14.0


# Integrator Parameters
timestep            0.5  ;# 0.5fs/step
rigidBonds          water  ;# needed for water models
waterModel          tip4
nonbondedFreq       2
fullElectFrequency  4  
stepspercycle       20 ;#default es 20.


# Constant Temperature Control
langevin            on   ;# do langevin dynamics
langevinDamping     1.0    ;# damping coefficient (gamma) of 1/ps
langevinTemp        $temperature
langevinHydrogen    off  ;# don't couple langevin bath to hydrogens

#rescaleFreq 2
#rescaleTemp $temperature
#reassignFreq 20
#reassignTemp $temperature

# Constant Pressure Control (variable volume)
useGroupPressure      no ;# needed for rigidBonds
useFlexibleCell       no
useConstantArea       no
langevinPiston        off ;# on/off
langevinPistonTarget  1.01325 ;#  in bar -> 1 atm
langevinPistonPeriod  100.0 ;# fs
langevinPistonDecay   20.0 ;# fs
langevinPistonTemp    $temperature

# Electrostatic Force Evaluation
#FullDirect   no
MSM                 yes ;# yes/no ; activar si no se usa condición de borde periódica
MSMGridSpacing      2.5  ;# very sensitive to performance, use this default 2.5
#MSMPadding 1.0
MSMzmin	-10.0
MSMzmax +89.0

# PME (for full-system periodic electrostatics)
PME                 no
PMEGridSpacing      1.0
#manual grid definition
#PMEGridSizeX        45
#PMEGridSizeY        45
#PMEGridSizeZ        48

# Output
outputName          $outputname
restartfreq         100000  ;# 500steps = every 1ps
dcdfreq             20000
outputEnergies      2000
XSTfreq             20000


#############################################################
## EXTRA PARAMETERS                                        ##
#############################################################
fixedAtoms on
fixedAtomsForces on
fixedAtomsCol O

#TCL BC
tclBC on
tclBCScript {
set tclBCScript tcl-z-wall.tcl
source $tclBCScript 
}
#tclBCArgs{}

# Spherical boundary conditions
sphericalBC         off
sphericalBCcenter   30.3081743413, 28.8049907121, 15.353994423
sphericalBCr1       26.0
sphericalBCk1       10
sphericalBCexp1     2

# Periodic boundary conditions
cellBasisVector1 41.5 0.0 0.0 ;# vector to the next image
cellBasisVector2 0.0 41.5 0.0
#cellBasisVector3 0.0 0.0 86.0
cellOrigin 20.75 20.75 43.0 ;# the *center* of the cell
wrapAll on
wrapNearest on
wrapWater on

#############################################################
## EXECUTION SCRIPT                                        ##
#############################################################

# Minimization
  minimize            20
# reinitvels          $temperature

run 28000000     ;#

